package com.guisebastiao.lifeshotsapi.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum BusinessCode {
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    TOO_MANY_REQUESTS("TOO_MANY_REQUESTS"),
    ROUTE_NOT_FOUND("ROUTE_NOT_FOUND"),
    BAD_REQUEST("BAD_REQUEST"),
    TOKEN_EXPIRED("TOKEN_EXPIRED"),
    SESSION_EXPIRED("SESSION_EXPIRED"),
    UNAUTHORIZED("UNAUTHORIZED"),
    NOT_FOUND("NOT_FOUND"),
    ACCESS_DENIED("ACCESS_DENIED"),
    CONFLICT("CONFLICT"),
    VALIDATION_ERROR("VALIDATION_ERROR"),
    FAILED_DEPENDENCY("FAILED_DEPENDENCY"),
    PRIVATE_PROFILE("PRIVATE_PROFILE"),
    APPLICATION_ACCESS_DENIED("APPLICATION_ACCESS_DENIED"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR");

    private final String value;
}
