ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_user_id_fkey;
ALTER TABLE profiles DROP COLUMN IF EXISTS user_id;

ALTER TABLE profiles ALTER COLUMN id DROP DEFAULT;

ALTER TABLE profiles ADD CONSTRAINT fk_profiles_user FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE;